### PR TITLE
Travis and AppVeyor CI

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by jayvdb** [comment]
See https://travis-ci.org/jayvdb/elib_run/builds/538394981 and https://ci.appveyor.com/project/jayvdb/elib-run/builds/24874057

**Comment by etcher-be** [comment]
Awesome !

Thanks a bunch mate :beers:

**Comment by jayvdb** [comment]
No worries.  Some weird release problem happening at https://ci.appveyor.com/project/etcher/elib-run/builds/24984926

And if you are using Windows at all, you should take a look at https://bitbucket.org/vinay.sajip/sarge/pull-requests/8/fix-windows-registry-lookup

backstory is https://gitlab.com/coala/package_manager/issues/233 - coala is Python 3 only, and has only very basic needs for command invocation at the moment, so a Python 3 wrapper around sarge would be nice, adding type safety, etc.

**Comment by etcher-be** [comment]
Don't worry about Appveyor, your build passes without a glitch.

My workflow on Appveyor uses https://github.com/etcher-be/epab as a highly customised builder, which complains about the Git repo having changed (`appveyor.yml`), but that's not a factor, your push is 100% valid. It's a lazy way for me to keep all my repo "clean", in sync and published with minimal human intervention. I never expected to see my tiny personal nonsense of a project used by someone else, it's awesome =)

I'm working on #36 to update all the requirements for the projects (my main source is `pipenv`, and I sync `requirements.txt` & `requirements-dev.txt` from the Pipfile using EPAB). Should be ready in a jiffy !

**Comment by jayvdb** [comment]
At @coala we have been building out @moremoban for that type of thing; it works pre-checkin rather than post-checkin, with a 'moban' job checking that there are no inconsistencies and any changes from upstream have been added.  https://gitlab.com/coala/mobans is where all the configuration management stuff is, for all the repos.

**Comment by etcher-be** [comment]
That's very interesting, thank you !

**Pull request merged**
